vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        user_image:
            uri_prefix: /uploads/user
            upload_destination: '%kernel.project_dir%/public/uploads/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
